// sidenav.jsx 
export const allBookTitles = [
    "Genesis",
    "Exodus",
    "Leviticus",
    "Numbers",
    "Deuteronomy",
    "Joshua",
    "Judges",
    "Ruth",
    "1&2Samuel",
    "1&2Kings",
    "1&2Chronicles",
    "Ezra",
    "Nehemiah",
    "Esther",
    "Job",
    "Psalms",
    "Proverbs:TheWayofWisdom",
    "Ecclesiastes",
    "SongofSongs",
    "Isaiah",
    "Jeremiah",
    "Lamentations",
    "Ezekiel",
    "Daniel",
    "Hosea",
    "Joel,Amos,Obadiah,Jonah,andMicah",
    "Nahum,Habakkuk,Zephaniah,andHaggai",
    "ZechariahandMalachi",
    "Matthew",
    "Mark",
    "Luke",
    "John",
    "ActsoftheApostles",
    "Romans",
    "1&2Corinthians",
    "Galatians",
    "Ephesians",
    "Philippians",
    "Colossians",
    "1&2Thessalonians",
    "1&2TimothyandTitus",
    "Philemon",
    "Hebrews",
    "James",
    "1&2Peter",
    "123John",
    "Jude",
    "Revelation",
    "Justice",
    "HymnsV",
    "TheSermonontheMount",
    "Lent2017:YouAreMine",
    "Advent2018:UntiltheSonofGodAppears",
    "ThisIstheGospel",
    "Lent2018:SeetheLord’sSalvation",
    "MourningandDancing",
    "2019Wrapped:SheReadsTruthYearinReview",
    "NamesofGod",
    "OpenYourBible//Launch-WeekSampler",
    "InSpirit&inTruth:AStudyofBiblicalWorship",
    "Advent2016:ChristWasBornforThis",
    "Lent2016",
    "Hymns",
    "TheResurrectedLife",
    "TheRisenChrist",
    "Lent2020:HisLoveEndures",
    "Jesus,KeepMeNearTheCross",
    "TheBeatitudes",
    "PsalmsforPrayer",
    "AttributesofGod",
    "PsalmsofRest",
    "TheLifeofMoses",
    "HymnsIV",
    "BecauseHeLives",
    "HymnsII",
    "TheMiraclesofJesus",
    "SongsfortheRoad:ThePsalmsofAscent",
    "Women&MenintheWord:OldTestament",
    "HymnsIII",
    "GiveThanks",
    "MakingRoom:AStudyofBiblicalHospitality",
    "IAm:StatementsofOurSavior",
    "WorthyofPraise",
    "Advent2017:JoytotheWorld",
    "HoldingTighttoPermanent",
    "Advent2019:AThrillofHope",
    "CountdowntoActs",
    "FruitoftheSpirit",
    "Advent2015:BornIsTheKing",
    "TheParablesofJesus",
    "GoTellItontheMountain",
    "HymnsofHope",
    "PsalmsofGratitude",
]

// sidenav.jsx 
export const allBookTitlesFormat = {
    "ZechariahandMalachi": "Zechariah & Malachi",
    "Nahum,Habakkuk,Zephaniah,andHaggai": "Nahum, Habakkuk, Zephaniah, & Haggai",
    "1&2Kings": "1 & 2 Kings",
    "SongofSongs": "Song of Songs",
    "Proverbs:TheWayofWisdom": "Proverbs",
    "1&2Samuel": "1 & 2 Samuel",
    "Joel,Amos,Obadiah,Jonah,andMicah": "Joel, Amos, Obadiah, Jonah, & Micah",
    "1&2Thessalonians": "1 & 2 Thessalonians",
    "1&2Peter": "1 & 2 Peter",
    "1&2TimothyandTitus": "1 & 2 Timothy, & Titus",
    "ActsoftheApostles": "Acts",
    "1&2Corinthians": "1 & 2 Corinthians",
    "HymnsV": 'Hymns V',
    "TheSermonontheMount": 'The Sermon on the Mount',
    "Lent2017:YouAreMine": 'Lent 2017',
    "Advent2018:UntiltheSonofGodAppears": 'Advent 2018',
    "ThisIstheGospel": 'This is the Gospel',
    "Lent2018:SeetheLord’sSalvation": 'Lent 2018',
    "MourningandDancing": 'Mourning & Dancing',
    "2019Wrapped:SheReadsTruthYearinReview": '2019 Wrapped (Year in Review)',
    "NamesofGod": 'Names of God',
    "InSpirit&inTruth:AStudyofBiblicalWorship": 'In Spirit & in Truth (Biblical Worship)',
    "Advent2016:ChristWasBornforThis": 'Advent 2016',
    "Lent2016": 'Lent 2016',
    "Hymns": 'Hymns I',
    "TheResurrectedLife": 'The Resurrected Life',
    "TheRisenChrist": 'The Risen Christ',
    "Lent2020:HisLoveEndures": 'Lent 2020',
    "Jesus,KeepMeNearTheCross": 'Jesus, Keep Me Near The Cross',
    "TheBeatitudes": 'The Beatitudes',
    "PsalmsforPrayer": 'Psalms for Prayer',
    "AttributesofGod": 'Attributes of God',
    "PsalmsofRest": 'Psalms of Rest',
    "TheLifeofMoses": 'The Life of Moses',
    "HymnsIV": 'Hymns IV',
    "BecauseHeLives": 'Because He Lives',
    "HymnsII": 'Hymns II',
    "TheMiraclesofJesus": 'The Miracles of Jesus',
    "SongsfortheRoad:ThePsalmsofAscent": 'Psalms of Ascent',
    "Women&MenintheWord:OldTestament": 'Old Testament Women & Men',
    "HymnsIII": 'Hymns III',
    "GiveThanks": 'Give Thanks',
    "MakingRoom:AStudyofBiblicalHospitality": 'Making Room (Biblical Hospitality)',
    "IAm:StatementsofOurSavior": 'I Am (Statements of Our Savior)',
    "WorthyofPraise": 'Worthy of Praise',
    "Advent2017:JoytotheWorld": 'Advent 2017',
    "HoldingTighttoPermanent": 'Holding Tight to Permanent',
    "Advent2019:AThrillofHope": 'Advent 2019',
    "CountdowntoActs": 'Countdown to Acts',
    "FruitoftheSpirit": 'Fruit of the Spirit',
    "Advent2015:BornIsTheKing": 'Advent 2015',
    "TheParablesofJesus": 'The Parables of Jesus',
    "GoTellItontheMountain": 'Go Tell It on the Mountain',
    "HymnsofHope": 'Hymns of Hope',
    "PsalmsofGratitude": 'Psalms of Gratitude',
}

// categories.jsx 
export const bibleBooks = [
    "Genesis",
    "Exodus",
    "Leviticus",
    "Numbers",
    "Deuteronomy",
    "Joshua",
    "Judges",
    "Ruth",
    "1&2Samuel",
    "SecondSamuel",
    "1&2Kings",
    "SecondKings",
    "1&2Chronicles",
    "SecondChronicles",
    "Ezra",
    "Nehemiah",
    "Esther",
    "Job",
    "Psalm",
    "Proverbs:TheWayofWisdom",
    "Ecclesiastes",
    "SongofSongs",
    "Isaiah",
    "Jeremiah",
    "Lamentations",
    "Ezekiel",
    "Daniel",
    "Hosea",
    "Joel,Amos,Obadiah,Jonah,andMicah",
    "Amos",
    "Obadiah",
    "Jonah",
    "Micah",
    "Nahum,Habakkuk,Zephaniah,andHaggai",
    "Habakkuk",
    "Zephaniah",
    "Haggai",
    "ZechariahandMalachi",
    "Malachi",
    "Matthew",
    "Mark",
    "Luke",
    "John",
    "ActsoftheApostles",
    "Romans",
    "1&2Corinthians",
    "SecondCorinthians",
    "Galatians",
    "Ephesians",
    "Philippians",
    "Colossians",
    "1&2Thessalonians",
    "SecondThessalonians",
    "1&2TimothyandTitus",
    "SecondTimothy",
    "Titus",
    "Philemon",
    "Hebrews",
    "James",
    "1&2Peter",
    "SecondPeter",
    "123John",
    "SecondJohn",
    "ThirdJohn",
    "Jude",
    "Revelation"
]

// category_list_NT.jsx
export const NTbooks = [
    "Matthew",
    "Mark",
    "Luke",
    "John",
    "ActsoftheApostles",
    "Romans",
    "1&2Corinthians",
    "Galatians",
    "Ephesians",
    "Philippians",
    "Colossians",
    "1&2Thessalonians",
    "1&2TimothyandTitus",
    "Philemon",
    "Hebrews",
    "James",
    "1&2Peter",
    "123John",
    "Jude",
    "Revelation",
];

// category_list_NT.jsx
export const NTbookFormat = {
    "1&2thessalonians": "1 & 2 Thessalonians",
    "1&2peter": "1 & 2 Peter",
    "1&2timothyandtitus": "1 & 2 Timothy, & Titus",
    "actsoftheapostles": "Acts",
    "1&2corinthians": "1 & 2 Corinthians"
};

// category_list_OT.jsx
export const OTbooks = [
    "Genesis",
    "Exodus",
    "Leviticus",
    "Numbers",
    "Deuteronomy",
    "Joshua",
    "Judges",
    "Ruth",
    "1&2Samuel",
    "1&2Kings",
    "1&2Chronicles",
    "Ezra",
    "Nehemiah",
    "Esther",
    "Job",
    "Psalms",
    "Proverbs:TheWayofWisdom",
    "Ecclesiastes",
    "SongofSongs",
    "Isaiah",
    "Jeremiah",
    "Lamentations",
    "Ezekiel",
    "Daniel",
    "Hosea",
    "Joel,Amos,Obadiah,Jonah,andMicah",
    "Nahum,Habakkuk,Zephaniah,andHaggai",
    "ZechariahandMalachi",
];

// category_list_OT.jsx
export const OTbookFormat = {
    "zechariahandmalachi": "Zechariah & Malachi",
    "nahum,habakkuk,zephaniah,andhaggai": "Nahum, Habakkuk, Zephaniah, & Haggai",
    "1&2kings": "1 & 2 Kings",
    "songofsongs": "Song of Songs",
    "proverbs:thewayofwisdom": "Proverbs",
    "1&2samuel": "1 & 2 Samuel",
    "joel,amos,obadiah,jonah,andmicah": "Joel, Amos, Obadiah, Jonah, & Micah",
};

// category_list_Other.jsx
export const themeBooks = [
    "Justice",
    "HymnsV",
    "TheSermonontheMount",
    "ThisIstheGospel",
    "MourningandDancing",
    "NamesofGod",
    "OpenYourBible//Launch-WeekSampler",
    "InSpirit&inTruth:AStudyofBiblicalWorship",
    "Hymns",
    "TheResurrectedLife",
    "TheRisenChrist",
    "Lent2020:HisLoveEndures",
    "Jesus,KeepMeNearTheCross",
    "TheBeatitudes",
    "PsalmsforPrayer",
    "AttributesofGod",
    "PsalmsofRest",
    "TheLifeofMoses",
    "HymnsIV",
    "BecauseHeLives",
    "HymnsII",
    "TheMiraclesofJesus",
    "SongsfortheRoad:ThePsalmsofAscent",
    "Women&MenintheWord:OldTestament",
    "HymnsIII",
    "GiveThanks",
    "MakingRoom:AStudyofBiblicalHospitality",
    "IAm:StatementsofOurSavior",
    "WorthyofPraise",
    "HoldingTighttoPermanent",
    "Advent2019:AThrillofHope",
    "CountdowntoActs",
    "FruitoftheSpirit",
    "TheParablesofJesus",
    "GoTellItontheMountain",
    "HymnsofHope",
    "PsalmsofGratitude",
]

// category_list_Other.jsx
export const themeBookFormat = {
    "HymnsV": 'Hymns V',
    "TheSermonontheMount": 'The Sermon on the Mount',
    "Lent2017:YouAreMine": 'Lent 2017',
    "Advent2018:UntiltheSonofGodAppears": 'Advent 2018',
    "ThisIstheGospel": 'This is the Gospel',
    "Lent2018:SeetheLord’sSalvation": 'Lent 2018',
    "MourningandDancing": 'Mourning & Dancing',
    "2019Wrapped:SheReadsTruthYearinReview": '2019 Wrapped (Year in Review)',
    "NamesofGod": 'Names of God',
    "InSpirit&inTruth:AStudyofBiblicalWorship": 'In Spirit & in Truth (Biblical Worship)',
    "Advent2016:ChristWasBornforThis": 'Advent 2016',
    "Lent2016": 'Lent 2016',
    "Hymns": 'Hymns I',
    "TheResurrectedLife": 'The Resurrected Life',
    "TheRisenChrist": 'The Risen Christ',
    "Lent2020:HisLoveEndures": 'Lent 2020',
    "Jesus,KeepMeNearTheCross": 'Jesus, Keep Me Near The Cross',
    "TheBeatitudes": 'The Beatitudes',
    "PsalmsforPrayer": 'Psalms for Prayer',
    "AttributesofGod": 'Attributes of God',
    "PsalmsofRest": 'Psalms of Rest',
    "TheLifeofMoses": 'The Life of Moses',
    "HymnsIV": 'Hymns IV',
    "BecauseHeLives": 'Because He Lives',
    "HymnsII": 'Hymns II',
    "TheMiraclesofJesus": 'The Miracles of Jesus',
    "SongsfortheRoad:ThePsalmsofAscent": 'Psalms of Ascent',
    "Women&MenintheWord:OldTestament": 'Old Testament Women & Men',
    "HymnsIII": 'Hymns III',
    "GiveThanks": 'Give Thanks',
    "MakingRoom:AStudyofBiblicalHospitality": 'MakingRoom (Biblical Hospitality)',
    "IAm:StatementsofOurSavior": 'I Am (Statements of Our Savior)',
    "WorthyofPraise": 'Worthy of Praise',
    "Advent2017:JoytotheWorld": 'Advent 2017',
    "HoldingTighttoPermanent": 'Holding Tight to Permanent',
    "Advent2019:AThrillofHope": 'Advent 2019',
    "CountdowntoActs": 'Countdown to Acts',
    "FruitoftheSpirit": 'Fruit of the Spirit',
    "Advent2015:BornIsTheKing": 'Advent 2015',
    "TheParablesofJesus": 'The Parables of Jesus',
    "GoTellItontheMountain": 'Go Tell It on the Mountain',
    "HymnsofHope": 'Hymns of Hope',
    "PsalmsofGratitude": 'Psalms of Gratitude',
};